apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-cicd-app-deployment
spec:
  selector:
    matchLabels:
      app: my-cicd
  template:
    metadata:
      labels:
        app: my-cicd
    spec:
      containers:
        - name: my-cicd
          image: ${CICD_REGISTRY}/${REGISTRY_PROJECT_NAME}/${IMAGE_ID}:${IMAGE_TAG}  # replace with your container registry url
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8090

---
apiVersion: v1
kind: Service
metadata:
  name: my-cicd-app-service
spec:
  type: LoadBalancer
  selector:
    app: my-cicd
  ports:
    - port: 8090
      targetPort: 8090